import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";

const myFont = localFont({
  src: "../../public/fonts/futura.ttf", // Adjust the path if necessary
  // weight: "400", // Specify the weight if needed
  // style: "normal", // Specify the style if needed
  variable: "--font-futura", // Optional CSS variable for styling
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import CommandBar from "@/components/ui/CommandBar";
import Header from "@/components/ui/Header";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="pt-20">{children}</main>
        <CommandBar />
      </body>
    </html>
  );
}
